# Issue Porter Config File
# Use this to control the program

# USAGE
# Please create a copy of this config file called "config.toml",
# edit it, and then run `python3.12 src/main.py`

# See below config for technical details

[gitlab]
# Gitlab access token.
access_token = "SECRET"

# Domain to access the gitlab server.
domain = "gitlab.com"

# Id of project, can be found next to name on project page.
project = 278964

# Only issues with this label will be transferred.
# If empty all issues will be transferred.
transfer_label = "Transfer"

# Transfer closed issues?
transfer_closed = false


[github]
# Github access token.
access_token = "SECRET"

# Target project to port the issues to.
project = "gitlabhq/gitlabhq"

# Label which will be applied to any issue that gets transferred
ported_issue_label = ""

# [porter]
# # Print debug messages
# debug = true

# TECHNICAL DETAILS

# The way the program works is it first runs through gitlab pulling in all the issues.
# It skips issues if they don't have the [gitlab.label] label.
# These then get mapped straight over to github, where we import them, only appending a link to the old issue.
# We then do a second pass, editing each issue to update links and strip the link back.
# You can still access the old issue because github keeps track of issues history.
# All additional issues are ported straight over 1:1